[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[program:wss]
command=python3 -u -m server.__main__
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=10

[program:web]
command=python3 -u -m server.web_service
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=5
